### ISSUE TITLE
Conversion of DCYL detector gives broken files

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/pymchelper#259] opened 2017-10-12 18:10 UTC
I've generated some energy-depth spectra for 200 MeV proton beams using DCYL scorer and SH12A v0.7.1.

Using:
```
*----0---><----1---><----2---><----3---><----4---><----5---><----6--->
DCYL             0.0       0.0       0.0      10.0       7.0      30.0
                   1         1       300        -1      DOSE    ex_dcyl_dose_en_p
                 0.0     220.0       300              ENERGY
```

I obtain:

![ex_dcyl_dose_en_p](https://user-images.githubusercontent.com/7374733/31511861-511348b8-af89-11e7-8ba4-6df590536b8e.png)

Clearly is seen that the depth and energy axis are swapped.

If I change number of bins in energy and depth then it gets completely broken:
```
*----0---><----1---><----2---><----3---><----4---><----5---><----6--->
DCYL             0.0       0.0       0.0      10.0       7.0      30.0
                   1         1       300        -1      DOSE    ex_dcyl_dose_en_p
                 0.0     220.0       220              ENERGY
```

![ex_dcyl_dose_en_p](https://user-images.githubusercontent.com/7374733/31511879-6268c43a-af89-11e7-9160-73314718a3f5.png)

**Comment by nbassler** [comment] 2017-10-16 19:26
Duplicate of #205 ?

**Comment by grzanka** [comment] 2017-10-16 20:05
@nbassler Yes, its a duplicate

**Closed** 2017-10-19 18:08 UTC
Labels: in progress, Type: bug
